---
- name: Ensure .bash_profile prerequisite exists
  copy:
    content: ""
    dest: ~/.bash_profile
    force: no

- name: Install nvm {{ nvm.version }} automagically
  shell: curl -o- https://raw.githubusercontent.com/creationix/nvm/{{ nvm.version }}/install.sh | bash
  args:
    executable: /bin/bash

- name: Install node {{ nvm.node_version }} painlessly
  shell: source ~/.bash_profile && nvm install {{ nvm.node_version }}
  args:
    executable: /bin/bash

- name: Set default node to {{ nvm.node_version }}
  shell: source ~/.bash_profile && nvm alias default {{ nvm.node_version }} --no-colors
  args:
    executable: /bin/bash