---
- name: Install problematic desktop environment
  hosts: all
  gather_facts: no

  vars:
    cask_packages:
      - dropbox
      - gotomeeting
      - itau
      - libreoffice
      - slack

  tasks:
    - name: Install Homebrew Cask packages
      homebrew_cask: name={{ item }} state=present
      with_items: "{{ cask_packages }}"

