---
- name: Install criptocurrencies environment
  hosts: all
  gather_facts: no

  vars:
    bitcoind_plist: "templates/Library/LaunchAgents/org.bitcoin.bitcoind.plist"
    launch_agents_path: "~/Library/LaunchAgents/"
    packages:
      - bitcoin

  tasks:
    - name: Install Homebrew packages
      homebrew: name={{ item }} state=latest
      with_items: "{{ packages }}"

    - name: Install bitcoind plist
      copy: src="{{ bitcoind_plist }}" dest="{{ launch_agents_path }}" mode=600
