---
- name: Install databases
  hosts: all

  vars:
    packages:
      - elasticsearch
      - postgres
      - redis

  tasks:
    - name: Install Homebrew packages
      homebrew: name={{ item }} state=latest
      with_items: "{{ packages }}"