---
- name: Install desktop environment
  hosts: all
  gather_facts: no

  vars:
    packages:
      - macvim

    cask_packages:
      - adobe-acrobat-reader
      - caffeine
      - discord
      - docker
      - electrum
      - firefox
      - google-chrome
      - iterm2
      - shiftit
      - skitch
      - skype
      - telegram
      - visual-studio-code

  tasks:
    - name: Install Homebrew packages
      homebrew: name={{ packages }} state=latest

    - name: Install Homebrew Cask packages
      homebrew_cask: name={{ item }} state=latest
      with_items: "{{ cask_packages }}"

