---
- name: Install desktop environment
  hosts: all
  gather_facts: no

  vars:
    packages:
      - adobe-acrobat-reader
      - brave-browser
      - caffeine
      - clockify
      - discord
      - docker
      - electrum
      - google-chrome
      - graphiql
      - inkscape
      - iterm2
      - macvim
      - obs
      - postman
      - rectangle
      - rescuetime
      - skitch
      - skype
      - telegram
      - visual-studio-code

  tasks:
    - community.general.homebrew:
      name: Install Homebrew packages
      homebrew: name={{ packages }} state=latest

