---
- name: Install oh-my-zsh and configure ssh
  hosts: all
  gather_facts: yes

# Inspired by https://github.com/RaymiiOrg/ansible/blob/master/oh-my-zsh/ohmyzsh.yml

  vars:
    oh_my_zsh_repo: "https://github.com/robbyrussell/oh-my-zsh.git"
    oh_my_zsh_dir: "~/.oh-my-zsh"
    src_ssh_config: "templates/shell/ssh-config"
    dst_ssh_config: "~/.ssh/config"

    dotfiles:
      - "templates/shell/.zshrc"
      - "templates/shell/.asdfrc"
      - "templates/shell/.tool-versions"
      - "templates/shell/.default-gems"
      - "templates/shell/.gitconfig"

  tasks:
    - name: Clone oh-my-zsh repository
      git: repo="{{ oh_my_zsh_repo }}" dest="{{ oh_my_zsh_dir }}" version=master
      tags:
        - clone

    - name: Install ssh_config
      copy: src="{{ src_ssh_config }}" dest="{{ dst_ssh_config }}" mode=0600
      tags:
        - ssh_config

    - name: Install dotfiles to user directory
      copy: src="{{ item }}" dest="{{ ansible_user_dir }}" mode=0640
      loop: "{{ dotfiles }}"
      tags:
        - dotfiles

    # - name: Set zsh as default shell
    #   user: name={{ ansible_user_id }} shell=/bin/zsh
    # chsh -s /bin/zsh
