---
- name: Setup homebrew taps
  hosts: all
  gather_facts: no

  vars:
    taps:
      - homebrew/cask-versions
      - homebrew/core
      - thoughtbot/formulae
      - heroku/brew

  tasks:
    - name: Add Homebrew taps
      homebrew_tap: name={{ item }} state=present
      with_items: "{{ taps }}"
