---
- name: Install terminal environment
  hosts: all

  vars:
    topsecret_repo: "git@gitlab.com:mauriciovieira/top-secret.git"
    topsecret_path: "~/Repositories/gitlab.com/mauriciovieira/top-secret"
    screenshots_path: "~/Pictures/Screenshots"

    packages:
      - ag
      - docker-compose
      - docker-machine
      - ffmpeg
      - ghc
      - gifsicle
      - git
      - heroku
      - htop
      - hub
      - imagemagick
      - mosh
      - parity
      - passpie
      - pyenv
      - pyenv-virtualenv
      - pyenv-virtualenvwrapper
      - shellcheck
      - wget
      - yarn

    cask_packages:
      - java
      - ngrok
      - virtualbox

    rubygems:
      - travis

    unwanted_packages:
      - htop-osx

    # todo:
    #   - rvm
    #   - nvm
    #   - yadr

  tasks:
    - name: Ensure {{ topsecret_path }} exists
      file: path={{ topsecret_path }} state=directory

    - name: Clone / update top-secret repository
      git: repo={{ topsecret_repo }} dest="{{ topsecret_path }}" version=master

    - name: Install top-secret stuff
      shell: chdir="{{ topsecret_path }}" make install

    - name: Uninstall Homebrew packages
      homebrew: name={{ item }} state=absent
      with_items: "{{ unwanted_packages }}"

    - name: Install Homebrew packages
      homebrew: name={{ item }} state=latest
      with_items: "{{ packages }}"

    - name: Install ruby gems
      gem: name={{ item }} state=present
      with_items: "{{ rubygems }}"

    - name: Install Homebrew Cask packages
      homebrew_cask: name={{ item }} state=installed
      with_items: "{{ cask_packages }}"

    - name: Ensure {{ screenshots_path }} exists
      file: path={{ screenshots_path }} state=directory

    - name: Set screenshots location
      shell: defaults write com.apple.screencapture location {{ screenshots_path }}
