---
- name: Install terminal environment
  hosts: all
  gather_facts: no

  vars:
    vscode_settings: "templates/Library/ApplicationSupport/Code/User/settings.json"
    vscode_settings_path: "~/Library/Application Support/Code/User/"
    screenshots_path: "~/Pictures/Screenshots"

    packages:
      - act
      - ag
      - autojump
      - bats
      - certbot
      - cmake
      - composer
      - ffmpeg
      - ghc
      - gifsicle
      - git
      - git-flow-avh
      - gnu-indent
      - heroku
      - htop
      - hub
      - imagemagick
      - jq
      - mosh
      - mr
      - parity
      - passpie
      - pv
      - shellcheck
      - terminal-notifier
      - wget
      - yarn
      - zlib
      - zsh
      - zsh-completions

    cask_packages:
      - java
      - ngrok
      - vagrant
      - virtualbox

  tasks:
    - name: Install Homebrew packages
      homebrew: name={{ packages }} state=latest
      tags:
        - homebrew
        - homebrew_only

    - name: Install Homebrew Cask packages
      homebrew_cask: name={{ cask_packages }} state=installed
      tags:
        - homebrew
        - homebrew_cask

    - name: Ensure {{ screenshots_path }} exists
      file: path={{ screenshots_path }} state=directory

    - name: Set screenshots location
      shell: defaults write com.apple.screencapture location {{ screenshots_path }}

    - name: Install vscode settings
      copy: src="{{ vscode_settings }}" dest="{{ vscode_settings_path }}" mode=0640
